name: Bug Report
description: File a bug report for Steam Inventory Advanced Filter
labels: [bug]
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Please provide a clear and concise description of the problem.
      placeholder: Describe the issue in detail.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, userscript manager (Tampermonkey/Violentmonkey/etc), and script version.
      placeholder: e.g. Chrome 125, Tampermonkey, v1.0.0
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or log output here.
      placeholder: Any other details...
    validations:
      required: false
