name: Feature Request
description: Suggest an idea or improvement for Steam Inventory Advanced Filter
labels: [enhancement]
title: '[Feature]: '
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature or improvement!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature or improvement would you like to see?
      placeholder: Describe the feature or improvement in detail.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Why is this feature important? What problem does it solve?
      placeholder: Explain the use case or motivation.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or mockups here.
      placeholder: Any other details...
    validations:
      required: false
